config/routes.rb
Inventory::Application.routes.draw do

  resources :sites

  resources :products

  resources :manufacturers

  resources :rings

  resources :devices

  devise_for :users, skip: :registrations

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resource :pages, only: [:home]

  root :to => 'pages#home'
end
#== Route Map
# Generated on 07 Jul 2012 16:25
#
#                            POST       /sites(.:format)                   sites#create
#                   new_site GET        /sites/new(.:format)               sites#new
#                  edit_site GET        /sites/:id/edit(.:format)          sites#edit
#                       site GET        /sites/:id(.:format)               sites#show
#                            PUT        /sites/:id(.:format)               sites#update
#                            DELETE     /sites/:id(.:format)               sites#destroy
#                   products GET        /products(.:format)                products#index
#                            POST       /products(.:format)                products#create
#                new_product GET        /products/new(.:format)            products#new
#               edit_product GET        /products/:id/edit(.:format)       products#edit
#                    product GET        /products/:id(.:format)            products#show
#                            PUT        /products/:id(.:format)            products#update
#                            DELETE     /products/:id(.:format)            products#destroy
#              manufacturers GET        /manufacturers(.:format)           manufacturers#index
#                            POST       /manufacturers(.:format)           manufacturers#create
#           new_manufacturer GET        /manufacturers/new(.:format)       manufacturers#new
#          edit_manufacturer GET        /manufacturers/:id/edit(.:format)  manufacturers#edit
#               manufacturer GET        /manufacturers/:id(.:format)       manufacturers#show
#                            PUT        /manufacturers/:id(.:format)       manufacturers#update
#                            DELETE     /manufacturers/:id(.:format)       manufacturers#destroy
#                      rings GET        /rings(.:format)                   rings#index
#                            POST       /rings(.:format)                   rings#create
#                   new_ring GET        /rings/new(.:format)               rings#new
#                  edit_ring GET        /rings/:id/edit(.:format)          rings#edit
#                       ring GET        /rings/:id(.:format)               rings#show
#                            PUT        /rings/:id(.:format)               rings#update
#                            DELETE     /rings/:id(.:format)               rings#destroy
#                    devices GET        /devices(.:format)                 devices#index
#                            POST       /devices(.:format)                 devices#create
#                 new_device GET        /devices/new(.:format)             devices#new
#                edit_device GET        /devices/:id/edit(.:format)        devices#edit
#                     device GET        /devices/:id(.:format)             devices#show
#                            PUT        /devices/:id(.:format)             devices#update
#                            DELETE     /devices/:id(.:format)             devices#destroy
#           new_user_session GET        /users/sign_in(.:format)           devise/sessions#new
#               user_session POST       /users/sign_in(.:format)           devise/sessions#create
#       destroy_user_session DELETE     /users/sign_out(.:format)          devise/sessions#destroy
#              user_password POST       /users/password(.:format)          devise/passwords#create
#          new_user_password GET        /users/password/new(.:format)      devise/passwords#new
#         edit_user_password GET        /users/password/edit(.:format)     devise/passwords#edit
#                            PUT        /users/password(.:format)          devise/passwords#update
#            admin_dashboard            /admin(.:format)                   admin/dashboard#index
#                admin_users GET        /admin/users(.:format)             admin/users#index
#                            POST       /admin/users(.:format)             admin/users#create
#             new_admin_user GET        /admin/users/new(.:format)         admin/users#new
#            edit_admin_user GET        /admin/users/:id/edit(.:format)    admin/users#edit
#                 admin_user GET        /admin/users/:id(.:format)         admin/users#show
#                            PUT        /admin/users/:id(.:format)         admin/users#update
#                            DELETE     /admin/users/:id(.:format)         admin/users#destroy
#             admin_comments GET        /admin/comments(.:format)          admin/comments#index
#                            POST       /admin/comments(.:format)          admin/comments#create
#          new_admin_comment GET        /admin/comments/new(.:format)      admin/comments#new
#         edit_admin_comment GET        /admin/comments/:id/edit(.:format) admin/comments#edit
#              admin_comment GET        /admin/comments/:id(.:format)      admin/comments#show
#                            PUT        /admin/comments/:id(.:format)      admin/comments#update
#                            DELETE     /admin/comments/:id(.:format)      admin/comments#destroy
#     new_admin_user_session GET        /admin/login(.:format)             active_admin/devise/sessions#new
#         admin_user_session POST       /admin/login(.:format)             active_admin/devise/sessions#create
# destroy_admin_user_session DELETE|GET /admin/logout(.:format)            active_admin/devise/sessions#destroy
#        admin_user_password POST       /admin/password(.:format)          active_admin/devise/passwords#create
#    new_admin_user_password GET        /admin/password/new(.:format)      active_admin/devise/passwords#new
#   edit_admin_user_password GET        /admin/password/edit(.:format)     active_admin/devise/passwords#edit
#                            PUT        /admin/password(.:format)          active_admin/devise/passwords#update
#                       root            /                                  pages#home

app/models/device.rb
class Device < ActiveRecord::Base

  KINDS = %w(aggregation ring node access)

  attr_accessible :name, :kind, :product_id, :site_id

  # Model Relationships
  belongs_to :product
  belongs_to :site

  # Model Validations
  validates_presence_of :name, :product_id, :site_id
  validates :kind, inclusion: { in: KINDS, message: "%{value} is not a valid" }
end

app/controllers/devices_controller.rb
class DevicesController < InheritedResources::Base
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.haml
= form_for @device do |f|
  -if @device.errors.any?
    #error_explanation
      %h2= "#{pluralize(@device.errors.count, "error")} prohibited this device from being saved:"
      %ul
        - @device.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :kind
    =f.select(:kind, Device::KINDS, {include_blank: true})
  .field
    = f.label :product_id
    = f.collection_select :product_id, Product.order(:name), :id, :name, {}, {multiple: false, class: "chzn-select", "data-placeholder" => "Select Product..."}
  .field
    = f.label :site_id
    = f.collection_select :site_id, Site.order(:name), :id, :name, {}, {multiple: false, class: "chzn-select", "data-placeholder" => "Select Site..."}
  .actions
    = f.submit 'Save'

app/views/devices/edit.html.haml
%h1 Editing device

= render 'form'

= link_to 'Show', @device
\|
= link_to 'Back', devices_path

app/views/devices/index.html.haml
%h1 Listing devices

%table
  %tr
    %th Name
    %th Kind
    %th Product
    %th Site
    %th
    %th
    %th

  - @devices.each do |device|
    %tr
      %td= device.name
      %td= device.kind
      %td= device.product_id
      %td= device.site_id
      %td= link_to 'Show', device
      %td= link_to 'Edit', edit_device_path(device)
      %td= link_to 'Destroy', device, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Device', new_device_path

app/views/devices/new.html.haml
%h1 New device

= render 'form'

= link_to 'Back', devices_path

app/views/devices/show.html.haml
%p
  %b Name:
  = @device.name
%p
  %b Kind:
  = @device.kind
%p
  %b Product:
  = @device.product.name
%p
  %b Site:
  = @device.site.name

= link_to 'Edit', edit_device_path(@device)
\|
= link_to 'Back', devices_path